title: Welcome to my first GitHub Pages
theme: minima
author: KhunLwin
email: khunlwin.2018@gmail.com
description: > # I'm a new user of GitHub. Now, I'm trying to get my first GitHub Pages.

# social links
twitter_username: Khun-Cho-Lwin
github_username:  KhunLwin

show_excerpts: true # set to false to remove excerpts on the homepage
